name: Development Checkup for SimpleRisk Minimal (PHP 8.1)

on:
  pull_request:
    branches:
      - 'master'

jobs:
  oci-check:
    name: 'OCI Check'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        run: |
          docker build -t simplerisk/simplerisk-minimal:php81 -f simplerisk-minimal/php81/Dockerfile simplerisk-minimal

      - name: Run Dockle
        uses: hands-lab/dockle-action@v1
        with:
          image: "simplerisk/simplerisk-minimal:php81"
          exit-code: '1'
          exit-level: FATAL
