name: Development Checkup for SimpleRisk (Ubuntu 22.04-Jammy)

on:
  pull_request:
    branches:
      - 'master'

jobs:
  oci-check:
    name: 'OCI Check'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        run: |
          docker build -t simplerisk/simplerisk:jammy -f simplerisk/jammy/Dockerfile simplerisk

      - name: Run Dockle
        uses: hands-lab/dockle-action@v1
        with:
          image: "simplerisk/simplerisk:jammy"
          exit-code: '1'
          exit-level: FATAL
